# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
java_version=21

# Mod properties
maven_group=com.github.tyty0817
mod_id=bruhmod
mod_name=Epic Justinian Bacon
version=0.0.1
mod_author=Justin, Tyler, Rhys
description=wizard 101 mod
license=CC0
credits=kaupenjoe
icon_path=assets/${mod_id}/textures/item/mythril.png

# Minecraft and mod loaders
minecraft_version=1.21.1
minecraft_version_range=[1.21, 1.21.1]

# Minecraft vanilla+mappings
neo_form_version=20240808.144430
parchment_version=2024.11.17

# NeoForge
neoforge_version=21.1.215
neoforge_loader_version_range=[4,)

# Fabric
fabric_loader_version=0.16.14
fabric_version=0.116.1

# Libraries
patchouli_version=1.21-87
accessories_version=1.1.0-beta.7
geckolib_version=4.7.3

# Compatibility
modmenu_version=11.0.3
jei_version=19.18.10.218
